CREATE TABLE ME (
    KOD VARCHAR(5) NOT NULL UNIQUE,
    NEV VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY (KOD)
);

CREATE TABLE CIKK (
    CSZ VARCHAR(14) NOT NULL UNIQUE,
    NEV VARCHAR(150) NOT NULL UNIQUE,
    ME VARCHAR(5) NOT NULL,
    PRIMARY KEY (CSZ),
    FOREIGN KEY (ME) REFERENCES ME(KOD)
);

CREATE TABLE TETELEK (
    ID INT AUTO_INCREMENT NOT NULL UNIQUE,
    CSZ VARCHAR(14) NOT NULL,
    MENNYISEG NUMERIC(15, 2) NOT NULL,
    EGYSEGAR NUMERIC(15, 2) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CSZ) REFERENCES CIKK(CSZ)
);

INSERT INTO ME (KOD, NEV) VALUES
('KG', 'Kilogramm'),
('DB', 'Darab'),
('L', 'Liter'),
('M', 'Méter');

INSERT INTO CIKK (CSZ, NEV, ME) VALUES
('CSZ001', 'Rákcsali', 'KG'),
('CSZ002', 'Nádi Nyalóka', 'DB'),
('CSZ003', 'Vadvirág tápoldat', 'L');

INSERT INTO TETELEK (CSZ, MENNYISEG, EGYSEGAR) VALUES
('CSZ001', 20.00, 499.00),
('CSZ002', 50.00, 299.00),
('CSZ003', 5.50, 1190.00);

SELECT * FROM ME;
SELECT * FROM CIKK;
SELECT * FROM TETELEK;



